#!/bin/sh
gnuplot gpl_n_days_incidence-job.8
gnuplot gpl_incidence-job.8
gnuplot gpl_immunity-job.8
gnuplot gpl_reproduction-job.8
gnuplot gpl_infection-job.8
gnuplot gpl_lethality-job.8
#gnuplot covid.compare
