#!/bin/sh
gnuplot gpl_n_days_incidence-job.1
gnuplot gpl_incidence-job.1
gnuplot gpl_immunity-job.1
gnuplot gpl_reproduction-job.1
gnuplot gpl_infection-job.1
gnuplot gpl_lethality-job.1
#gnuplot covid.compare
