#!/bin/sh
#
IDX="0"
REPR="3.000"
BRST="no_bursts"
#
amadeus -n ${IDX} -f par.init${IDX}
cp 7_days_incidence_R0=${REPR}_job_no_${IDX} ${BRST}
cp inc_R0=${REPR}_job_no_${IDX} inc_${BRST}
cp imm_R0=${REPR}_job_no_${IDX} imm_${BRST}
#
gnuplot gpl_n_days_incidence_job_no_${IDX}
gnuplot gpl_incidence_job_no_${IDX}
gnuplot gpl_immunity_job_no_${IDX}
gnuplot gpl_reproduction_job_no_${IDX}
gnuplot gpl_infection_job_no_${IDX}
gnuplot gpl_lethality_job_no_${IDX}
