#!/bin/sh
gnuplot gpl_n_days_incidence-job.51
gnuplot gpl_incidence-job.51
gnuplot gpl_immunity-job.51
gnuplot gpl_reproduction-job.51
gnuplot gpl_infection-job.51
gnuplot gpl_lethality-job.51
#gnuplot covid.compare
