#!/bin/sh
gnuplot gpl_n_days_incidence-job.21
gnuplot gpl_incidence-job.21
gnuplot gpl_immunity-job.21
gnuplot gpl_reproduction-job.21
gnuplot gpl_infection-job.21
gnuplot gpl_lethality-job.21
#gnuplot covid.compare
