#!/bin/sh
gnuplot gpl_n_days_incidence-job.19
gnuplot gpl_incidence-job.19
gnuplot gpl_immunity-job.19
gnuplot gpl_reproduction-job.19
gnuplot gpl_infection-job.19
gnuplot gpl_lethality-job.19
#gnuplot covid.compare
