#!/bin/sh
gnuplot gpl_n_days_incidence-job.39
gnuplot gpl_incidence-job.39
gnuplot gpl_immunity-job.39
gnuplot gpl_reproduction-job.39
gnuplot gpl_infection-job.39
gnuplot gpl_lethality-job.39
#gnuplot covid.compare
