#!/bin/sh
gnuplot gpl_n_days_incidence-job.31
gnuplot gpl_incidence-job.31
gnuplot gpl_immunity-job.31
gnuplot gpl_reproduction-job.31
gnuplot gpl_infection-job.31
gnuplot gpl_lethality-job.31
#gnuplot covid.compare
