#!/bin/sh
gnuplot gpl_n_days_incidence-job.56
gnuplot gpl_incidence-job.56
gnuplot gpl_immunity-job.56
gnuplot gpl_reproduction-job.56
gnuplot gpl_infection-job.56
gnuplot gpl_lethality-job.56
#gnuplot covid.compare
