#!/bin/sh
gnuplot gpl_n_days_incidence-job.20
gnuplot gpl_incidence-job.20
gnuplot gpl_immunity-job.20
gnuplot gpl_reproduction-job.20
gnuplot gpl_infection-job.20
gnuplot gpl_lethality-job.20
#gnuplot covid.compare
