#!/bin/sh
gnuplot gpl_n_days_incidence-job.0
gnuplot gpl_incidence-job.0
gnuplot gpl_immunity-job.0
gnuplot gpl_reproduction-job.0
gnuplot gpl_infection-job.0
gnuplot gpl_lethality-job.0
#gnuplot covid.compare
