#!/bin/sh
gnuplot gpl_n_days_incidence_job.50
gnuplot gpl_incidence_job.50
gnuplot gpl_immunity_job.50
gnuplot gpl_reproduction_job.50
gnuplot gpl_infection_job.50
gnuplot gpl_lethality_job.50
#gnuplot covid.compare
