#!/bin/sh
gnuplot gpl_n_days_incidence-job.42
gnuplot gpl_incidence-job.42
gnuplot gpl_immunity-job.42
gnuplot gpl_reproduction-job.42
gnuplot gpl_infection-job.42
gnuplot gpl_lethality-job.42
#gnuplot covid.compare
