#!/bin/sh
gnuplot gpl_n_days_incidence_job.54
gnuplot gpl_incidence_job.54
gnuplot gpl_immunity_job.54
gnuplot gpl_reproduction_job.54
gnuplot gpl_infection_job.54
gnuplot gpl_lethality_job.54
#gnuplot covid.compare
