#!/bin/sh
gnuplot gpl_n_days_incidence-job.44
gnuplot gpl_incidence-job.44
gnuplot gpl_immunity-job.44
gnuplot gpl_reproduction-job.44
gnuplot gpl_infection-job.44
gnuplot gpl_lethality-job.44
#gnuplot covid.compare
