#!/bin/sh
gnuplot gpl_n_days_incidence-job.59
gnuplot gpl_incidence-job.59
gnuplot gpl_immunity-job.59
gnuplot gpl_reproduction-job.59
gnuplot gpl_infection-job.59
gnuplot gpl_lethality-job.59
#gnuplot covid.compare
