#!/bin/sh
gnuplot gpl_n_days_incidence_job.32
gnuplot gpl_incidence_job.32
gnuplot gpl_immunity_job.32
gnuplot gpl_reproduction_job.32
gnuplot gpl_infection_job.32
gnuplot gpl_lethality_job.32
#gnuplot covid.compare
