#!/bin/sh
gnuplot gpl_n_days_incidence-job.18
gnuplot gpl_incidence-job.18
gnuplot gpl_immunity-job.18
gnuplot gpl_reproduction-job.18
gnuplot gpl_infection-job.18
gnuplot gpl_lethality-job.18
#gnuplot covid.compare
