#!/bin/sh
gnuplot gpl_n_days_incidence_job.31
gnuplot gpl_incidence_job.31
gnuplot gpl_immunity_job.31
gnuplot gpl_reproduction_job.31
gnuplot gpl_infection_job.31
gnuplot gpl_lethality_job.31
#gnuplot covid.compare
