#!/bin/sh
gnuplot gpl_n_days_incidence-job.32
gnuplot gpl_incidence-job.32
gnuplot gpl_immunity-job.32
gnuplot gpl_reproduction-job.32
gnuplot gpl_infection-job.32
gnuplot gpl_lethality-job.32
#gnuplot covid.compare
