#!/bin/sh
gnuplot gpl_n_days_incidence-job.38
gnuplot gpl_incidence-job.38
gnuplot gpl_immunity-job.38
gnuplot gpl_reproduction-job.38
gnuplot gpl_infection-job.38
gnuplot gpl_lethality-job.38
#gnuplot covid.compare
