#!/bin/sh
gnuplot gpl_n_days_incidence-job.50
gnuplot gpl_incidence-job.50
gnuplot gpl_immunity-job.50
gnuplot gpl_reproduction-job.50
gnuplot gpl_infection-job.50
gnuplot gpl_lethality-job.50
#gnuplot covid.compare
