#!/bin/sh
gnuplot gpl_n_days_incidence_job.36
gnuplot gpl_incidence_job.36
gnuplot gpl_immunity_job.36
gnuplot gpl_reproduction_job.36
gnuplot gpl_infection_job.36
gnuplot gpl_lethality_job.36
#gnuplot covid.compare
