#!/bin/sh
gnuplot gpl_n_days_incidence-job.35
gnuplot gpl_incidence-job.35
gnuplot gpl_immunity-job.35
gnuplot gpl_reproduction-job.35
gnuplot gpl_infection-job.35
gnuplot gpl_lethality-job.35
#gnuplot covid.compare
