#!/bin/sh
gnuplot gpl_n_days_incidence_job.18
gnuplot gpl_incidence_job.18
gnuplot gpl_immunity_job.18
gnuplot gpl_reproduction_job.18
gnuplot gpl_infection_job.18
gnuplot gpl_lethality_job.18
#gnuplot covid.compare
