#!/bin/sh
gnuplot gpl_n_days_incidence-job.49
gnuplot gpl_incidence-job.49
gnuplot gpl_immunity-job.49
gnuplot gpl_reproduction-job.49
gnuplot gpl_infection-job.49
gnuplot gpl_lethality-job.49
#gnuplot covid.compare
