#!/bin/sh
# Transmission time = 5 days
# parameters cf. par.init21-29
#---------------------------
#gnuplot 7_Days_INC_1080_Days
#gnuplot 7_Days_INC_200_Days
gnuplot 7_Days_INC_180_Days
#gnuplot 7_Days_INC_120_Days
#gnuplot 7_Days_INC_90_Days
#gnuplot 7_Days_INC_14_Days
#gnuplot 7_Days_INC_7_Days
#gnuplot INC_1080_Days
#gnuplot INC_200_Days
gnuplot INC_180_Days
#gnuplot INC_120_Days
#gnuplot INC_90_Days
#gnuplot INC_14_Days
#gnuplot INC_7_Days
#---------------------------
# Transmission time = 7 days
# parameters cf. par.init1-9
#---------------------------
#gnuplot 7_days_inc_1080_days
#gnuplot 7_days_inc_200_days
#gnuplot 7_days_inc_120_days
#gnuplot 7_days_inc_90_days
#gnuplot inc_1080_days
#gnuplot inc_200_days
#gnuplot inc_120_days
#gnuplot inc_90_days
