#!/bin/sh
amadeus -n 0 -f par.init0
cp 7_days_incidence_R0=.9400_job_no_0 Timm=Infinite
cp inc_R0=.9400_job_no_0 Ti=Infinite
#gnuplot gpl_n_days_incidence_job_no_0
#gnuplot gpl_incidence_job_no_0
#gnuplot gpl_immunity_job_no_0
#gnuplot gpl_reproduction_job_no_0
#gnuplot gpl_infection_job_no_0
#gnuplot gpl_lethality_job_no_0
