#!/bin/sh
amadeus -n 5 -f par.init5
cp 7_days_incidence_R0=.9400_job_no_5 Timm=210_Days
cp inc_R0=.9400_job_no_5 Ti=210_Days
#gnuplot gpl_n_days_incidence_job_no_5
#gnuplot gpl_incidence_job_no_5
#gnuplot gpl_immunity_job_no_5
#gnuplot gpl_reproduction_job_no_5
#gnuplot gpl_infection_job_no_5
#gnuplot gpl_lethality_job_no_5
