#!/bin/sh
amadeus -n 7 -f par.init7
cp 7_days_incidence_R0=.9400_job_no_7 Timm=360_Days
cp inc_R0=.9400_job_no_7 Ti=360_Days
#gnuplot gpl_n_days_incidence_job_no_7
#gnuplot gpl_incidence_job_no_7
#gnuplot gpl_immunity_job_no_7
#gnuplot gpl_reproduction_job_no_7
#gnuplot gpl_infection_job_no_7
#gnuplot gpl_lethality_job_no_7
