#!/bin/sh
#
IDX="14"
REPR=".7500"
#
amadeus -n ${IDX} -f par.init${IDX}
cp 7_days_incidence_R0=${REPR}_job_no_${IDX} R0=${REPR}
cp inc_R0=${REPR}_job_no_${IDX} r0=${REPR}
cp imm_R0=${REPR}_job_no_${IDX} imm_R0=${REPR}
cp rpd_R0=${REPR}_job_no_${IDX} rep_R0=${REPR}
#
gnuplot gpl_n_days_incidence_job_no_${IDX}
gnuplot gpl_incidence_job_no_${IDX}
gnuplot gpl_immunity_job_no_${IDX}
gnuplot gpl_reproduction_job_no_${IDX}
gnuplot gpl_infection_job_no_${IDX}
gnuplot gpl_lethality_job_no_${IDX}
