#!/bin/sh
amadeus -n 19 -f par.init19
cp 7_days_incidence_R0=2.875 R=2.875_T=oo
gnuplot gpl_n_days_incidence_job.19
gnuplot gpl_incidence_job.19
gnuplot gpl_immunity_job.19
gnuplot gpl_reproduction_job.19
gnuplot gpl_infection_job.19
gnuplot gpl_lethality_job.19
#gnuplot covid.compare
