#!/bin/sh
amadeus -n 13 -f par.init13
cp 7_days_incidence_R0=1.000 R=1.000_T=180d
gnuplot gpl_n_days_incidence_job.13
gnuplot gpl_incidence_job.13
gnuplot gpl_immunity_job.13
gnuplot gpl_reproduction_job.13
gnuplot gpl_infection_job.13
gnuplot gpl_lethality_job.13
#gnuplot covid.compare
