#!/bin/sh
amadeus -n 14 -f par.init14
cp 7_days_incidence_R0=.8750 R=.8750_T=180d
gnuplot gpl_n_days_incidence_job.14
gnuplot gpl_incidence_job.14
gnuplot gpl_immunity_job.14
gnuplot gpl_reproduction_job.14
gnuplot gpl_infection_job.14
gnuplot gpl_lethality_job.14
#gnuplot covid.compare
