#!/bin/sh
amadeus -n 20 -f par.init20
cp 7_days_incidence_R0=2.750 R=2.750_T=oo
gnuplot gpl_n_days_incidence_job.20
gnuplot gpl_incidence_job.20
gnuplot gpl_immunity_job.20
gnuplot gpl_reproduction_job.20
gnuplot gpl_infection_job.20
gnuplot gpl_lethality_job.20
#gnuplot covid.compare
