#!/bin/sh
amadeus -n 22 -f par.init22
cp 7_days_incidence_R0=2.250_job_no_22 R=2.250_T=oo
gnuplot gpl_n_days_incidence_job_no_22
gnuplot gpl_incidence_job_no_22
gnuplot gpl_immunity_job_no_22
gnuplot gpl_reproduction_job_no_22
gnuplot gpl_infection_job_no_22
gnuplot gpl_lethality_job_no_22
#gnuplot covid.compare
