#!/bin/sh
amadeus -n 21 -f par.init21
cp 7_days_incidence_R0=2.500_job_no_21 R=2.500_T=oo
gnuplot gpl_n_days_incidence_job_no_21
gnuplot gpl_incidence_job_no_21
gnuplot gpl_immunity_job_no_21
gnuplot gpl_reproduction_job_no_21
gnuplot gpl_infection_job_no_21
gnuplot gpl_lethality_job_no_21
#gnuplot covid.compare
