#!/bin/sh
amadeus -n 27 -f par.init27
cp 7_days_incidence_R0=1.250_job_no_17 R=1.250_T=oo
gnuplot gpl_n_days_incidence_job_no_27
gnuplot gpl_incidence_job_no_27
gnuplot gpl_immunity_job_no_27
gnuplot gpl_reproduction_job_no_27
gnuplot gpl_infection_job_no_27
gnuplot gpl_lethality_job_no_27
#gnuplot covid.compare
