#!/bin/sh
amadeus -n 24 -f par.init24
cp 7_days_incidence_R0=1.750_job_no_24 R=1.750_T=oo
gnuplot gpl_n_days_incidence_job_no_24
gnuplot gpl_incidence_job_no_24
gnuplot gpl_immunity_job_no_24
gnuplot gpl_reproduction_job_no_24
gnuplot gpl_infection_job_no_24
gnuplot gpl_lethality_job_no_24
#gnuplot covid.compare
