#!/bin/sh
amadeus -n 31 -f par.init31
cp 7_days_incidence_R0=.5000_job_no_31 R=.5000_T=oo
gnuplot gpl_n_days_incidence_job_no_31
gnuplot gpl_incidence_job_no_31
gnuplot gpl_immunity_job_no_31
gnuplot gpl_reproduction_job_no_31
gnuplot gpl_infection_job_no_31
gnuplot gpl_lethality_job_no_31
#gnuplot covid.compare
