#!/bin/sh
amadeus -n 3 -f par.init3
cp 7_days_incidence_R0=2.875_job_no_3 R=2.875_T=180d
gnuplot gpl_n_days_incidence_job_no_3
gnuplot gpl_incidence_job_no_3
gnuplot gpl_immunity_job_no_3
gnuplot gpl_reproduction_job_no_3
gnuplot gpl_infection_job_no_3
gnuplot gpl_lethality_job_no_3
#gnuplot covid.compare
