#!/bin/sh
amadeus -n 4 -f par.init4
cp 7_days_incidence_R0=2.750_job_no_4 R=2.750_T=180d
gnuplot gpl_n_days_incidence_job_no_4
gnuplot gpl_incidence_job_no_4
gnuplot gpl_immunity_job_no_4
gnuplot gpl_reproduction_job_no_4
gnuplot gpl_infection_job_no_4
gnuplot gpl_lethality_job_no_4
#gnuplot covid.compare
