#!/bin/sh
amadeus -n 8 -f par.init8
cp 7_days_incidence_R0=1.750 R=1.750_T=180d
gnuplot gpl_n_days_incidence_job.8
gnuplot gpl_incidence_job.8
gnuplot gpl_immunity_job.8
gnuplot gpl_reproduction_job.8
gnuplot gpl_infection_job.8
gnuplot gpl_lethality_job.8
#gnuplot covid.compare
