#!/bin/sh
amadeus -n 1 -f par.init1
cp 7_days_incidence_R0=3.000_job_no_1 T=infinite
gnuplot gpl_n_days_incidence_job_no_1
gnuplot gpl_incidence_job_no_1
gnuplot gpl_immunity_job_no_1
gnuplot gpl_reproduction_job_no_1
gnuplot gpl_infection_job_no_1
gnuplot gpl_lethality_job_no_1
