#!/bin/sh
amadeus -n 10 -f par.init10
cp 7_days_incidence_R0=.8200_job_no_10 VR=200
cp inc_R0=.8200_job_no_10 vr=200
#gnuplot gpl_n_days_incidence_job_no_10
#gnuplot gpl_incidence_job_no_10
#gnuplot gpl_immunity_job_no_10
#gnuplot gpl_reproduction_job_no_10
#gnuplot gpl_infection_job_no_10
#gnuplot gpl_lethality_job_no_10
