#!/bin/sh
amadeus -n 18 -f par.init18
cp 7_days_incidence_R0=.8200_job_no_18 VR=360
cp inc_R0=.8200_job_no_18 vr=360
#gnuplot gpl_n_days_incidence_job_no_18
#gnuplot gpl_incidence_job_no_18
#gnuplot gpl_immunity_job_no_18
#gnuplot gpl_reproduction_job_no_18
#gnuplot gpl_infection_job_no_18
#gnuplot gpl_lethality_job_no_18
