#!/bin/sh
amadeus -n 15 -f par.init15
cp 7_days_incidence_R0=.8200_job_no_15 VR=300
cp inc_R0=.8200_job_no_15 vr=300
#gnuplot gpl_n_days_incidence_job_no_15
#gnuplot gpl_incidence_job_no_15
#gnuplot gpl_immunity_job_no_15
#gnuplot gpl_reproduction_job_no_15
#gnuplot gpl_infection_job_no_15
#gnuplot gpl_lethality_job_no_15
