#!/bin/sh
amadeus -n 19 -f par.init19
cp 7_days_incidence_R0=.8200_job_no_19 VR=380
cp inc_R0=.8200_job_no_19 vr=380
#gnuplot gpl_n_days_incidence_job_no_19
#gnuplot gpl_incidence_job_no_19
#gnuplot gpl_immunity_job_no_19
#gnuplot gpl_reproduction_job_no_19
#gnuplot gpl_infection_job_no_19
#gnuplot gpl_lethality_job_no_19
