#!/bin/sh
amadeus -n 12 -f par.init12
cp 7_days_incidence_R0=.8200_job_no_12 VR=240
cp inc_R0=.8200_job_no_12 vr=240
#gnuplot gpl_n_days_incidence_job_no_12
#gnuplot gpl_incidence_job_no_12
#gnuplot gpl_immunity_job_no_12
#gnuplot gpl_reproduction_job_no_12
#gnuplot gpl_infection_job_no_12
#gnuplot gpl_lethality_job_no_12
