#!/bin/sh
amadeus -n 2 -f par.init2
cp 7_days_incidence_R0=.8200_job_no_2 VR=40
cp inc_R0=.8200_job_no_2 vr=40
#gnuplot gpl_n_days_incidence_job_no_2
#gnuplot gpl_incidence_job_no_2
#gnuplot gpl_immunity_job_no_2
#gnuplot gpl_reproduction_job_no_2
#gnuplot gpl_infection_job_no_2
#gnuplot gpl_lethality_job_no_2
