#!/bin/sh
amadeus -n 20 -f par.init20
cp 7_days_incidence_R0=.8200_job_no_20 VR=400
cp inc_R0=.8200_job_no_20 vr=400
#gnuplot gpl_n_days_incidence_job_no_20
#gnuplot gpl_incidence_job_no_20
#gnuplot gpl_immunity_job_no_20
#gnuplot gpl_reproduction_job_no_20
#gnuplot gpl_infection_job_no_20
#gnuplot gpl_lethality_job_no_20
