#!/bin/sh
amadeus -n 23 -f par.init23
cp 7_days_incidence_R0=.8200_job_no_23 VR=150
cp inc_R0=.8200_job_no_23 vr=150
#gnuplot gpl_n_days_incidence_job_no_23
#gnuplot gpl_incidence_job_no_23
#gnuplot gpl_immunity_job_no_23
#gnuplot gpl_reproduction_job_no_23
#gnuplot gpl_infection_job_no_23
#gnuplot gpl_lethality_job_no_23
