#!/bin/sh
amadeus -n 22 -f par.init22
cp 7_days_incidence_R0=.8200_job_no_22 VR=50
cp inc_R0=.8200_job_no_22 vr=50
#gnuplot gpl_n_days_incidence_job_no_22
#gnuplot gpl_incidence_job_no_22
#gnuplot gpl_immunity_job_no_22
#gnuplot gpl_reproduction_job_no_22
#gnuplot gpl_infection_job_no_22
#gnuplot gpl_lethality_job_no_22
