#!/bin/sh
amadeus -n 7 -f par.init7
cp 7_days_incidence_R0=.8200_job_no_7 VR=140
cp inc_R0=.8200_job_no_7 vr=140
#gnuplot gpl_n_days_incidence_job_no_7
#gnuplot gpl_incidence_job_no_7
#gnuplot gpl_immunity_job_no_7
#gnuplot gpl_reproduction_job_no_7
#gnuplot gpl_infection_job_no_7
#gnuplot gpl_lethality_job_no_7
