#!/bin/sh
gnuplot gpl_n_days_incidence-job.4
gnuplot gpl_incidence-job.4
gnuplot gpl_immunity-job.4
gnuplot gpl_reproduction-job.4
gnuplot gpl_infection-job.4
gnuplot gpl_lethality-job.4
#gnuplot covid.compare
