#!/bin/sh
#
IDX="5"
REPR=".8600"
RATE="80"
#
amadeus -n ${IDX} -f par.init${IDX}
cp 7_days_incidence_R0=${REPR}_job_no_${IDX} VR=${RATE}
cp inc_R0=${REPR}_job_no_${IDX} vr=${RATE}
#
gnuplot gpl_n_days_incidence_job_no_${IDX}
gnuplot gpl_incidence_job_no_${IDX}
gnuplot gpl_immunity_job_no_${IDX}
gnuplot gpl_reproduction_job_no_${IDX}
gnuplot gpl_vaccination_job_no_${IDX}
gnuplot gpl_infection_job_no_${IDX}
gnuplot gpl_lethality_job_no_${IDX}
