#!/bin/sh
amadeus -n 0 -f par.init0
cp 7_days_incidence_R0=.8200_job_no_0 VR=0
cp inc_R0=.8200_job_no_0 vr=0
#gnuplot gpl_n_days_incidence_job_no_0
#gnuplot gpl_incidence_job_no_0
#gnuplot gpl_immunity_job_no_0
#gnuplot gpl_reproduction_job_no_0
#gnuplot gpl_infection_job_no_0
#gnuplot gpl_lethality_job_no_0
