#!/bin/sh
amadeus -n 11 -f par.init11
cp 7_days_incidence_R0=.8200_job_no_11 VR=220
cp inc_R0=.8200_job_no_11 vr=220
#gnuplot gpl_n_days_incidence_job_no_11
#gnuplot gpl_incidence_job_no_11
#gnuplot gpl_immunity_job_no_11
#gnuplot gpl_reproduction_job_no_11
#gnuplot gpl_infection_job_no_11
#gnuplot gpl_lethality_job_no_11
