#!/bin/sh
amadeus -n 17 -f par.init17
cp 7_days_incidence_R0=.8200_job_no_17 VR=340
cp inc_R0=.8200_job_no_17 vr=340
#gnuplot gpl_n_days_incidence_job_no_17
#gnuplot gpl_incidence_job_no_17
#gnuplot gpl_immunity_job_no_17
#gnuplot gpl_reproduction_job_no_17
#gnuplot gpl_infection_job_no_17
#gnuplot gpl_lethality_job_no_17
