#!/bin/sh
gnuplot gpl_n_days_incidence-job.9
gnuplot gpl_incidence-job.9
gnuplot gpl_immunity-job.9
gnuplot gpl_reproduction-job.9
gnuplot gpl_infection-job.9
gnuplot gpl_lethality-job.9
#gnuplot covid.compare
