#!/bin/sh
gnuplot gpl_n_days_incidence-job.7
gnuplot gpl_incidence-job.7
gnuplot gpl_immunity-job.7
gnuplot gpl_reproduction-job.7
gnuplot gpl_infection-job.7
gnuplot gpl_lethality-job.7
#gnuplot covid.compare
