#!/bin/sh
amadeus -n 2 -f par.init2
gnuplot gpl_n_days_incidence_job.2
gnuplot gpl_incidence_job.2
gnuplot gpl_immunity_job.2
gnuplot gpl_reproduction_job.2
gnuplot gpl_infection_job.2
gnuplot gpl_lethality_job.2
#gnuplot covid.compare
