#!/bin/sh
#----------------------------------------------------
REPR="1.500"
APX="r"
#----------------------------------------------------
#
IDX="11"
RATE="0"
#
amadeus -n ${IDX} -f par.init${IDX}${APX}
#mv par.log${IDX} par.log${IDX}${APX}
cp 7_days_incidence_R0=${REPR}_job_no_${IDX} vr=${RATE}
#
gnuplot gpl_n_days_incidence_job_no_10
gnuplot gpl_n_days_incidence_job_no_11
