#!/bin/sh
gnuplot gpl_n_days_incidence-job.6
gnuplot gpl_incidence-job.6
gnuplot gpl_immunity-job.6
gnuplot gpl_reproduction-job.6
gnuplot gpl_infection-job.6
gnuplot gpl_lethality-job.6
#gnuplot covid.compare
