#!/bin/sh
gnuplot gpl_n_days_incidence-job.48
gnuplot gpl_incidence-job.48
gnuplot gpl_immunity-job.48
gnuplot gpl_reproduction-job.48
gnuplot gpl_infection-job.48
gnuplot gpl_lethality-job.48
#gnuplot covid.compare
