#!/bin/sh
gnuplot gpl_n_days_incidence-job.40
gnuplot gpl_incidence-job.40
gnuplot gpl_immunity-job.40
gnuplot gpl_reproduction-job.40
gnuplot gpl_infection-job.40
gnuplot gpl_lethality-job.40
#gnuplot covid.compare
