#!/bin/sh
gnuplot gpl_n_days_incidence-job.41
gnuplot gpl_incidence-job.41
gnuplot gpl_immunity-job.41
gnuplot gpl_reproduction-job.41
gnuplot gpl_infection-job.41
gnuplot gpl_lethality-job.41
#gnuplot covid.compare
