#!/bin/sh
gnuplot gpl_n_days_incidence-job.5
gnuplot gpl_incidence-job.5
gnuplot gpl_immunity-job.5
gnuplot gpl_reproduction-job.5
gnuplot gpl_infection-job.5
gnuplot gpl_lethality-job.5
#gnuplot covid.compare
