#!/bin/sh
gnuplot gpl_n_days_incidence-job.45
gnuplot gpl_incidence-job.45
gnuplot gpl_immunity-job.45
gnuplot gpl_reproduction-job.45
gnuplot gpl_infection-job.45
gnuplot gpl_lethality-job.45
#gnuplot covid.compare
