#!/bin/sh
gnuplot gpl_n_days_incidence-job.52
gnuplot gpl_incidence-job.52
gnuplot gpl_immunity-job.52
gnuplot gpl_reproduction-job.52
gnuplot gpl_infection-job.52
gnuplot gpl_lethality-job.52
#gnuplot covid.compare
