#!/bin/sh
gnuplot gpl_n_days_incidence-job.26
gnuplot gpl_incidence-job.26
gnuplot gpl_immunity-job.26
gnuplot gpl_reproduction-job.26
gnuplot gpl_infection-job.26
gnuplot gpl_lethality-job.26
#gnuplot covid.compare
