#!/bin/sh
gnuplot gpl_n_days_incidence-job.43
gnuplot gpl_incidence-job.43
gnuplot gpl_immunity-job.43
gnuplot gpl_reproduction-job.43
gnuplot gpl_infection-job.43
gnuplot gpl_lethality-job.43
#gnuplot covid.compare
