#!/bin/sh
gnuplot gpl_n_days_incidence-job.17
gnuplot gpl_incidence-job.17
gnuplot gpl_immunity-job.17
gnuplot gpl_reproduction-job.17
gnuplot gpl_infection-job.17
gnuplot gpl_lethality-job.17
#gnuplot covid.compare
