#!/bin/sh
gnuplot gpl_n_days_incidence-job.24
gnuplot gpl_incidence-job.24
gnuplot gpl_immunity-job.24
gnuplot gpl_reproduction-job.24
gnuplot gpl_infection-job.24
gnuplot gpl_lethality-job.24
#gnuplot covid.compare
