#!/bin/sh
gnuplot gpl_n_days_incidence-job.37
gnuplot gpl_incidence-job.37
gnuplot gpl_immunity-job.37
gnuplot gpl_reproduction-job.37
gnuplot gpl_infection-job.37
gnuplot gpl_lethality-job.37
#gnuplot covid.compare
