#!/bin/sh
gnuplot gpl_n_days_incidence-job.2
gnuplot gpl_incidence-job.2
gnuplot gpl_immunity-job.2
gnuplot gpl_reproduction-job.2
gnuplot gpl_infection-job.2
gnuplot gpl_lethality-job.2
#gnuplot covid.compare
