#!/bin/sh
gnuplot gpl_n_days_incidence-job.11
gnuplot gpl_incidence-job.11
gnuplot gpl_immunity-job.11
gnuplot gpl_reproduction-job.11
gnuplot gpl_infection-job.11
gnuplot gpl_lethality-job.11
#gnuplot covid.compare
