#!/bin/sh
amadeus -n 17 -f par.init17
cp 7_days_incidence_R0=3.250_job_no_17 R=3.250_T=oo
gnuplot gpl_n_days_incidence_job_no_17
gnuplot gpl_incidence_job_no_17
gnuplot gpl_immunity_job_no_17
gnuplot gpl_reproduction_job_no_17
gnuplot gpl_infection_job_no_17
gnuplot gpl_lethality_job_no_17
#gnuplot covid.compare
