#!/bin/sh
amadeus -n 19 -f par.init19
cp 7_days_incidence_R0=2.875_job_no_19 R=2.875_T=oo
gnuplot gpl_n_days_incidence_job_no_19
gnuplot gpl_incidence_job_no_19
gnuplot gpl_immunity_job_no_19
gnuplot gpl_reproduction_job_no_19
gnuplot gpl_infection_job_no_19
gnuplot gpl_lethality_job_no_19
#gnuplot covid.compare
