#!/bin/sh
amadeus -n 14 -f par.init14
cp 7_days_incidence_R0=.8750_job_no_14 R=.8750_T=90d
gnuplot gpl_n_days_incidence_job_no_14
gnuplot gpl_incidence_job_no_14
gnuplot gpl_immunity_job_no_14
gnuplot gpl_reproduction_job_no_14
gnuplot gpl_infection_job_no_14
gnuplot gpl_lethality_job_no_14
#gnuplot covid.compare
