#!/bin/sh
amadeus -n 16 -f par.init16
cp 7_days_incidence_R0=.5000_job_no_16 R=.5000_T=90d
gnuplot gpl_n_days_incidence_job_no_16
gnuplot gpl_incidence_job_no_16
gnuplot gpl_immunity_job_no_16
gnuplot gpl_reproduction_job_no_16
gnuplot gpl_infection_job_no_16
gnuplot gpl_lethality_job_no_16
#gnuplot covid.compare
