#!/bin/sh
amadeus -n 1 -f par.init1
cp 7_days_incidence_R0=3.250 R=3.250_T=90d
gnuplot gpl_n_days_incidence_job.1
gnuplot gpl_incidence_job.1
gnuplot gpl_immunity_job.1
gnuplot gpl_reproduction_job.1
gnuplot gpl_infection_job.1
gnuplot gpl_lethality_job.1
#gnuplot covid.compare
