#!/bin/sh
amadeus -n 12 -f par.init12
cp 7_days_incidence_R0=1.125 R=1.125_T=90d
gnuplot gpl_n_days_incidence_job.12
gnuplot gpl_incidence_job.12
gnuplot gpl_immunity_job.12
gnuplot gpl_reproduction_job.12
gnuplot gpl_infection_job.12
gnuplot gpl_lethality_job.12
#gnuplot covid.compare
