#!/bin/sh
amadeus -n 12 -f par.init12
cp 7_days_incidence_R0=1.125_job_no_12 R=1.125_T=90d
gnuplot gpl_n_days_incidence_job_no_12
gnuplot gpl_incidence_job_no_12
gnuplot gpl_immunity_job_no_12
gnuplot gpl_reproduction_job_no_12
gnuplot gpl_infection_job_no_12
gnuplot gpl_lethality_job_no_12
#gnuplot covid.compare
