#!/bin/sh
amadeus -n 21 -f par.init21
cp 7_days_incidence_R0=2.500 R=2.500_T=oo
gnuplot gpl_n_days_incidence_job.21
gnuplot gpl_incidence_job.21
gnuplot gpl_immunity_job.21
gnuplot gpl_reproduction_job.21
gnuplot gpl_infection_job.21
gnuplot gpl_lethality_job.21
#gnuplot covid.compare
