#!/bin/sh
amadeus -n 20 -f par.init20
cp 7_days_incidence_R0=2.750_job_no_20 R=2.750_T=oo
gnuplot gpl_n_days_incidence_job_no_20
gnuplot gpl_incidence_job_no_20
gnuplot gpl_immunity_job_no_20
gnuplot gpl_reproduction_job_no_20
gnuplot gpl_infection_job_no_20
gnuplot gpl_lethality_job_no_20
#gnuplot covid.compare
