#!/bin/sh
amadeus -n 23 -f par.init23
cp 7_days_incidence_R0=2.000 R=2.000_T=oo
gnuplot gpl_n_days_incidence_job.23
gnuplot gpl_incidence_job.23
gnuplot gpl_immunity_job.23
gnuplot gpl_reproduction_job.23
gnuplot gpl_infection_job.23
gnuplot gpl_lethality_job.23
#gnuplot covid.compare
