#!/bin/sh
amadeus -n 2 -f par.init2
cp 7_days_incidence_R0=3.000_job_no_2 R=3.000_T=90d
gnuplot gpl_n_days_incidence_job_no_2
gnuplot gpl_incidence_job_no_2
gnuplot gpl_immunity_job_no_2
gnuplot gpl_reproduction_job_no_2
gnuplot gpl_infection_job_no_2
gnuplot gpl_lethality_job_no_2
#gnuplot covid.compare
