#!/bin/sh
amadeus -n 29 -f par.init29
cp 7_days_incidence_R0=.8750_job_no_29 R=.8750_T=oo
gnuplot gpl_n_days_incidence_job_no_29
gnuplot gpl_incidence_job_no_29
gnuplot gpl_immunity_job_no_29
gnuplot gpl_reproduction_job_no_29
gnuplot gpl_infection_job_no_29
gnuplot gpl_lethality_job_no_29
#gnuplot covid.compare
