#!/bin/sh
amadeus -n 27 -f par.init27
cp 7_days_incidence_R0=1.250 R=1.250_T=oo
gnuplot gpl_n_days_incidence_job.27
gnuplot gpl_incidence_job.27
gnuplot gpl_immunity_job.27
gnuplot gpl_reproduction_job.27
gnuplot gpl_infection_job.27
gnuplot gpl_lethality_job.27
#gnuplot covid.compare
