#!/bin/sh
amadeus -n 28 -f par.init28
cp 7_days_incidence_R0=1.000_job_no_28 R=1.000_T=oo
gnuplot gpl_n_days_incidence_job_no_28
gnuplot gpl_incidence_job_no_28
gnuplot gpl_immunity_job_no_28
gnuplot gpl_reproduction_job_no_28
gnuplot gpl_infection_job_no_28
gnuplot gpl_lethality_job_no_28
#gnuplot covid.compare
