#!/bin/sh
amadeus -n 25 -f par.init25
cp 7_days_incidence_R0=1.500_job_no_25 R=1.500_T=oo
gnuplot gpl_n_days_incidence_job_no_25
gnuplot gpl_incidence_job_no_25
gnuplot gpl_immunity_job_no_25
gnuplot gpl_reproduction_job_no_25
gnuplot gpl_infection_job_no_25
gnuplot gpl_lethality_job_no_25
#gnuplot covid.compare
