#!/bin/sh
amadeus -n 25 -f par.init25
cp 7_days_incidence_R0=1.500 R=1.500_T=oo
gnuplot gpl_n_days_incidence_job.25
gnuplot gpl_incidence_job.25
gnuplot gpl_immunity_job.25
gnuplot gpl_reproduction_job.25
gnuplot gpl_infection_job.25
gnuplot gpl_lethality_job.25
#gnuplot covid.compare
