#!/bin/sh
amadeus -n 3 -f par.init3
cp 7_days_incidence_R0=2.875 R=2.875_T=90d
gnuplot gpl_n_days_incidence_job.3
gnuplot gpl_incidence_job.3
gnuplot gpl_immunity_job.3
gnuplot gpl_reproduction_job.3
gnuplot gpl_infection_job.3
gnuplot gpl_lethality_job.3
#gnuplot covid.compare
