#!/bin/sh
amadeus -n 30 -f par.init30
cp 7_days_incidence_R0=.7500 R=.7500_T=oo
gnuplot gpl_n_days_incidence_job.30
gnuplot gpl_incidence_job.30
gnuplot gpl_immunity_job.30
gnuplot gpl_reproduction_job.30
gnuplot gpl_infection_job.30
gnuplot gpl_lethality_job.30
#gnuplot covid.compare
