#!/bin/sh
amadeus -n 4 -f par.init4
cp 7_days_incidence_R0=2.750 R=2.750_T=90d
gnuplot gpl_n_days_incidence_job.4
gnuplot gpl_incidence_job.4
gnuplot gpl_immunity_job.4
gnuplot gpl_reproduction_job.4
gnuplot gpl_infection_job.4
gnuplot gpl_lethality_job.4
#gnuplot covid.compare
