#!/bin/sh
amadeus -n 6 -f par.init6
cp 7_days_incidence_R0=2.250 R=2.250_T=90d
gnuplot gpl_n_days_incidence_job.6
gnuplot gpl_incidence_job.6
gnuplot gpl_immunity_job.6
gnuplot gpl_reproduction_job.6
gnuplot gpl_infection_job.6
gnuplot gpl_lethality_job.6
#gnuplot covid.compare
