#!/bin/sh
amadeus -n 7 -f par.init7
cp 7_days_incidence_R0=2.000_job_noN7 R=2.000_T=90d
gnuplot gpl_n_days_incidence_job_no_7
gnuplot gpl_incidence_job_no_7
gnuplot gpl_immunity_job_no_7
gnuplot gpl_reproduction_job_no_7
gnuplot gpl_infection_job_no_7
gnuplot gpl_lethality_job_no_7
#gnuplot covid.compare
